### ISSUE TITLE
elixir-korea 그룹 어드민/관리자/Owner를 2인이상에게,,  

### ISSUE THREAD

**Issue by seungjin** [elixir-korea/elixir-korea.github.io#17]
모 당장은 아무도 신경을 안쓰는 수준이긴한데,, 
elixir-korea 그룹의 어드민? Owner 를 2명이상의.. 이왕이면 3명에게 할당헀으면합니다.
새로운 사용자의 가입이나 여러 Owner만의 기능을 여럿이서 공유함으로서 좀더 커뮤니티 업무의 분산화와 투명성을 이룰수 있지 않을가 합니다.

그렇다고 아직 모 커뮤니티 운영진이라고 사람을 지정할 정도는 아닌거 같고..
시작은 가볍게 하는게 좋을거 같습니다.

**Comment by nallwhy** [comment]
좋습니다! 일단은 초반에 많이 참여해주신 @seungjin , @Dalgona  두분 등록시켜드리겠습니다

**Comment by seungjin** [comment]
어드민? 그룹에 3분 정도가 좋아보입니다. 
아무래도 다들 직장일이나 개인일로 바빠지시면 나눠서 처리하면 좋으니간요.
또한 아무래도 우리들에게도 최대한 부담이 없어야 하니간, 
어드민그룹으로 일이 힘들다는 생각이 들면 후임자를 지정후에 자리를 전달해주시고 
잠시 쉬시?는 걸로 하면 어떨가요? 

이러면서 나름 운영규칙도 차근차근 만들어가는거죠. 모. 
일단,, 적어도 2019년보단 활성화 되었으면 소기의 목적은 달성이니.. 기대해보겠습니다.
