### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by nallwhy** [elixir-korea/elixir-korea.github.io#19]

**Comment by chulkilee** [comment]
어떤 구글 계정으로 할 예정인가요? 개인 구글 계정이 아니라 모임 소유여야 한다고 봅니다.

예전에 Google Apps 가 소규모에게 무료일때는 구입한 도메인에 물려서 썼는데, 이제는 유료군요..

팀으로 관리할 수 있는 간단한 analytics 가 있으면 그걸 이용해보면 좋겠습니다.

**Comment by chulkilee** [comment]
@nallwhy in https://github.com/elixir-korea/elixir-korea.github.io/pull/25

> @chulkilee
> GA 는 계정 소유의 개념이 없지 않나요?
> 필요한 분들 계정을 추가해드리면 동등한 것으로 알고 있습니다.



저도 GA 를 깊게 써보지는 않아서..

- [Understand the Analytics account structure - Analytics Help](https://support.google.com/analytics/topic/1102143?hl=en&ref_topic=1726911)
- [Hierarchy of organizations, accounts, users, properties, and views - Analytics Help](https://support.google.com/analytics/answer/1009618?hl=en&ref_topic=1102143)
- [Example account structures - Analytics Help](https://support.google.com/analytics/answer/1102152?hl=en&ref_topic=1102143)

보면, GA account 를 만들고 공유를 권한을 공유하는 것 같은데, [Organization](https://support.google.com/analytics/answer/7645246) 보면 요걸 써서 공유를 하는게 더 나은 방법 같네요. 현재 GA account 소유자분이 Organization 만들고 기존 GA account 추가하고, 멤버 몇 분을 organization 에 추가하면 어떨까요?

**Comment by seungjin** [comment]
일단 크게 힘을 들이지 않고 구현 가능한 방법으로 진행하되, 
종국에는 정보의 소수 독점이 아닌 커뮤니티 모두가 공유할수 있는 형태로 개방되어야 할듯합니다. 
이또한 좋은 프로젝트로 따로 후에 분리 되었으면 하는 마음입니다. 

위에 철기님 말씀대로 몇몇 맴버분들을 해당 관리자로 추가하고, 일년에 적어도 한번 해당 자료를 잘 정리해서 커뮤니티에 나누고 종국에는 자동으로 해당 정보를 공유하는 플랫폼을 만드는게 이상적인듯하네요.

**Comment by nallwhy** [comment]
네 그래서 PR approve 되고나면 원하시는 분들 다 추가해드릴 예정입니다. 여기 GitHub 처럼

**Comment by nallwhy** [comment]
Organization 은 GitHub 의 team 정도의 기능으로 이해하고 있습니다

**Comment by nallwhy** [comment]
그래서 어떤 구글계정이냐는 딱히 의미가 없는 것으로 압니다. 저희들 계정이 다 추가되고 플러스로 아무의미없는 공동계정을 추가할 수는 있습니다만

**Comment by seungjin** [comment]
일단 논의가 이루어진다음에 빠르게 진행하고,, 
나중에 자료를 공개하던지, 
따로 재미있는 프로젝트를 생성해서 재미있게 데이터를 공유하면 되니간요. 
어프르브 했습니다.

**Comment by nallwhy** [comment]
@chulkilee 어떻게 진행하면 좋을까요? 일단 GA 에 elixir-korea 계정은 추가했는데 어떤 분들을 조직관리자로 할지 그냥 사용자로 할지 등 결정해야할 것 같습니다.

**Comment by seungjin** [comment]
모 첫술에 배부를수야 있겠습니까..
꾸준히 만나면서(온/오프라인).. 의견조율하면서 더 바른 방향으로 발전하면 될듯합니다. 

아마 관건은 얼마나 우리가 "꾸준히" 해가냐일듯하네요.
