### ISSUE TITLE
gitter.im 설정

### ISSUE THREAD

**Issue by seungjin** [elixir-korea/elixir-korea.github.io#20]
https://elixir-lang.slack.com/archives/C0832A23G/p1577165845076000

@chulkilee 
Q&A 는 일단 요 채널이나 https://gitter.im/ 같은 걸로 붙이는걸로 하면 어떨까요? 괜찮게 논의되거나 Q&A 같은 걸 모아서 weekly posting 하는게 나을듯..  게시판은 쓰는 사람 없으면 오히려 마이너스라 왠만큼 필요하지 않으면 안붙이는데 한표 입니다 ㅎ
@jinkyou 나중에 시간 되시면 https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/faq.md#why-isnt-my-github-organisation-or-repos-appearing 요거 설정 해주시면 한번 테스트 해보겠습니다 (edited)

**Comment by nallwhy** [comment]
일단은 elixir-korea 채널이나 facebook 그룹으로의 유입을 유도하는 것이 좋지 않을까 싶어서 고민이네요 ㅎㅎ
우리나라 사람들이 gitter.im 에 안익숙하기도 하고

**Comment by chulkilee** [comment]
일단 slack 으로 합시다 :)
