### ISSUE TITLE
sitemap

### ISSUE THREAD

**Issue by nallwhy** [elixir-korea/elixir-korea.github.io#23]

**Comment by Dalgona** [comment]
Serum에 `Serum.Plugins.SitemapGenerator` 플러그인이 내장되어 있긴 한데, 블로그 포스트에 대해서만 항목을 만들어 줘서 제 쪽에서 플러그인을 개선하면 그걸 바로 사용할 수 있을 것 같아요. ㅎㅎ

**Comment by nallwhy** [comment]
네 ㅎㅎ 그거 봐서 첫 포스트 올리면서 적용해보려구요
