### ISSUE TITLE
2020년 2월 Meetup 준비 (2월19일)

### ISSUE THREAD

**Issue by seungjin** [elixir-korea/elixir-korea.github.io#34]
깃허브 이슈를 이렇게 써도 되는진 모르겠지만... ~ 한번 해보는거죠. 
2020년 2월 Meetup준비에 대한 쓰래드를 만들가 합니다. 

이제부터 매달 밋업에 5분에서 10분정도는 깃허브 이슈를 한번 다 같이 나열하면서 추가할건 추가하고 필요없는건 비우는 시간을 가져봤으면 하네요. 

그렇게 보면.. 모임 진행은 

1. 인사 (5분)
2. 깃허브 이슈 리뷰/상황에따라 pull request리뷰 시간도 되겠죠 (10분)
3. 세션 1 (20분)
4. 세션 2 (20분)
5. 라이트닝 토크 (10분)
6. 맺음 (5분)

이렇게 기본 템플릿?을 정해두고 70분 미팅을 기본으로 하면 어떨가요?
세션1과 세션2를 통합해 긴세션을 가져도 되고.. 긴세션을 2번 가지면서 미팅을 90분이나 2시간으로 확장해도 될듯하고.. 
물론 유동적으로 진행하게 되지만 기본뼈대를 두고 서로 수정/보완하면 어떨가 합니다.

**Comment by hongsw** [comment]
네 라이트닝 토크도 좋네요. 
슬랙 보다 여기가 더 소통이 활발한듯 합니다. +1

**Comment by seungjin** [comment]
이번 모임부터 돌아가면서 모임 서기?를 해볼가 합니다. 첫번째로 제가 2월 모임 기록을 남기는걸로 시작해보면 되겠네요.

**Comment by hongsw** [comment]
장소는 같은 장소 일까요?

**Comment by seungjin** [comment]
@hongsw 오는 2월달엔 승우님 회사에서 가능할가요? 지난번에 승우님회사를 이야기 하셔서..

**Comment by hongsw** [comment]
@seungjin 네 가능합니다. 자세한정보 올리겠습니다.

**Comment by seungjin** [comment]
Discord app의 monthy-meetup 으로..
