### ISSUE TITLE
SEO 문제 해결

### ISSUE THREAD

**Issue by nallwhy** [elixir-korea/elixir-korea.github.io#45]
og:title 등이 해당 글의 것이 아니라 모두 공통으로 만들어지고 있음
https://elixir-korea.github.io/posts/2020-04-25-how_to_setup_elixir_dev_env.html

**Comment by Dalgona** [comment]
메타태그 생성하는 부분을 개선해서 PR 올려봤는데, 리뷰해주시면 감사드리겠습니다 🙇🙇
